image: node:12

stages:
  - build
  - test

variables:
  CLICOLOR: "1"

build:
  stage: build
  script:
    - yarn --offline --frozen-lockfile --link-duplicates

test:
  stage: test
  script:
    - yarn --offline --frozen-lockfile --link-duplicates
    - yarn test
