image: node:12

stages:
  - build
  - test

variables:
  CLICOLOR: "1"

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache
    - node_modules
  policy: pull


.install: &install
  before_script:
    - yarn --offline --frozen-lockfile --link-duplicates

yarn_install:
  <<: *install
  stage: build
  cache:
    <<: *global_cache
    policy: push

yarn_test:
  <<: *install
  stage: test
  script:
    - yarn test
